version: '3.3'

services:
  web:
    image: 'timmy304681/trademap'
    container_name: trademap
    ports:
      - 3000:3000
    env_file: ./.env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - API_VERSION=$API_VERSION
      - HERE_API_KEY=$HERE_API_KEY
      - MAPTILER_API_KEY=$MAPTILER_API_KEY
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRE_TIME=$JWT_EXPIRE_TIME
      - SERVER_URL=$SERVER_URL
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MONGODB_URL=$MONGODB_URL
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_COLLECTION=$MONGODB_COLLECTION
      - REDIS_SERVER=$REDIS_SERVER
      - REDIS_USER=$REDIS_USER
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_PORT=$REDIS_PORT
      - REDIS_EXPIRE=$REDIS_EXPIRE
      - STATIC_FILES_URL=$STATIC_FILES_URL
      - IMAGES_URL=$IMAGES_URL
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
      - AWS_BUCKET_NAME=$AWS_BUCKET_NAME
      - LINE_NOTIFY_CLIENT_ID=$LINE_NOTIFY_CLIENT_ID
      - LINE_NOTIFY_CALLBACK_URL=$LINE_NOTIFY_CALLBACK_URL
      - LINE_NOTIFY_CLIENT_SECRET=$LINE_NOTIFY_CLIENT_SECRET
      - PEXELS_API_KEY=$PEXELS_API_KEY
